#!/bin/bash -eu

# configure inventory variables
for tmp_var in ${!ANSIBLE_TOWER_@}
do
	tmp_conf=${tmp_var##ANSIBLE_TOWER_}
	sed -i "s/^;*\s*${tmp_conf,,}=.*/${tmp_conf,,}='${!tmp_var}'/" /opt/tower-setup/inventory
done

# disable https if behind reverse proxy
if [[ "${ANSIBLE_TOWER_DISABLE_HTTPS:-no}" == "yes" ]]
then
	echo "nginx_disable_https='yes'" >>/opt/tower-setup/inventory
fi

# remove translations if requested
if [[ "${ANSIBLE_TOWER_REMOVE_TRANSLATIONS:-no}" == "yes" ]]
then
	rm -f /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/ui/static/languages/{es,fr,ja,nl}.json
	rm -fr /var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/locale/{es,fr,ja,nl}
fi

# setup instance
/opt/tower-setup/setup.sh

# start services
if [ "$1" == "ansible-tower" ]
then
    exec /usr/bin/supervisord -n -c /etc/supervisord.conf
else
    exec "$@"
fi
